---
name: AntiVPN
version: 0.0.1-BETA
main: ReinfyTeam\AntiVPN\AntiProxy
api: 5.0.0
src-namespace-prefix: ReinfyTeam\AntiVPN
description: "The best AntiProxy System for your PocketMine-MP Server!"
website: "https://github.com/ReinfyTeam/AntiVPN"
author: "ReinfyTeam"
authors: ["NhanAZ","xqwtxon","xVoiqMC"]
...
