#  ____           _            __           _____
---
# |  _ \    ___  (_)  _ __    / _|  _   _  |_   _|   ___    __ _   _ __ ___
# | |_) |  / _ \ | | | '_ \  | |_  | | | |   | |    / _ \  / _` | | '_ ` _ \
# |  _ <  |  __/ | | | | | | |  _| | |_| |   | |   |  __/ | (_| | | | | | | |
# |_| \_\  \___| |_| |_| |_| |_|    \__, |   |_|    \___|  \__,_| |_| |_| |_|
#                                   |___/
# Copyright ReinfyTeam (c) 2023
# <https://github.com/ReinfyTeam/AntiVPN>
#
# What is AntiVPN?
# ---
# This is an online plugin that blocks Proxy/VPN Services used by players, to
# manipulate their ip. This plugin will check them IP Address and these IP Address
# are being sent to <https://proxychecker.io> and <https://vpnapi.io/>. 
#
# How blocking works?
# ---
# The plugin sending a request with the player ip to <https://vpnapi.io/> to ensure
# the player doesn't use Proxy/VPN Services. These can prevent ip-ban bypassing, and DDOS attack..
#
# Why theres no offline in this plugin?
# ---
# Well, this plugin requesting to <https://vpnapi.io/> if your server has no connection
# within the proxy, the plugin wont work. I recommend you to use VPS or hosting provider for
# your minecraft server to ensure best expierience of the plugin.
#
#

# AntiVPN Main Configuration

# CONFIGURATION VERSION
# PLEASE DO NOT CHANGE THIS UNLESS YOU KNOW WHAT YOU ARE DOING OR 
# A DEVELOPER TOLD YOU TO CHANGE THIS. PLEASE DO NOT MODIFY THIS!
config-version: 0.0.1

# API KEY on vpnapi.io
# If you have an api key from vpnapi.io, get put it here.
# Leave blank to use standard/guess access to vpnapi.io which is limited to 100 request per day.
api-key: ""

# If player is detected using Proxy/VPN.
# Kick message will prompt to player when they using Proxy/VPN
kick-message: "&cProxy/VPN is not allowed in our server."

# BYPASS IP ADDRESS
# Bypass their ip address like localhost (127.0.0.1) user if any, or
# bypass their ip that provided.
bypass-ip:
    - "127.0.0.1"
    - "192.168.0.1"
    - "::"
    - "localhost"

# BYPASS PERMISSION
# Allows you to customize the bypass permission
# that permission plugin uses.
bypass-permission: "antivpn.bypass"

# BYPASS PLAYERS
# Allows you to bypass the player username from checking their ip.
# It is usefull for administrative actions.
bypass-players:
    - "xqwtxon"
    - "NhanAZ"
    - "xVoiqMC"
    - "BypassedAdminUser"
...